/**
 * Local offensive-word filter. Exact matches block source words from Datamuse;
 * longer substring terms catch accidental mixes (e.g. syllable joins).
 *
 * Keep lists lowercase a–z only. Prefer adding to BLOCKED_EXACT; use
 * BLOCKED_SUBSTRINGS only for terms that should never appear inside a word.
 */

/** Flip to compare filter cost. Filtering code stays; this only skips the check. */
export const CONTENT_FILTER_ENABLED = true;

const BLOCKED_EXACT = new Set([
  // Vulgar
  "anal",
  "anus",
  "arse",
  "ass",
  "asses",
  "asshole",
  "assholes",
  "ballsack",
  "bastard",
  "bastards",
  "bitch",
  "bitches",
  "bitchy",
  "blowjob",
  "bollocks",
  "boner",
  "boob",
  "boobs",
  "bugger",
  "bullshit",
  "clit",
  "clitoris",
  "cock",
  "cocks",
  "cocksucker",
  "coon",
  "crap",
  "cum",
  "cumming",
  "cunt",
  "cunts",
  "damn",
  "damned",
  "dick",
  "dickhole",
  "dicks",
  "dildo",
  "dildos",
  "dyke",
  "fag",
  "faggot",
  "faggots",
  "fags",
  "feck",
  "felch",
  "fellate",
  "fellatio",
  "feltch",
  "foreplay",
  "fuck",
  "fucked",
  "fucker",
  "fuckers",
  "fuckin",
  "fucking",
  "fucks",
  "fudgepacker",
  "goddamn",
  "hell",
  "homo",
  "jerkoff",
  "jizz",
  "labia",
  "muff",
  "nigga",
  "nigger",
  "niggers",
  "nutsack",
  "orgasm",
  "penis",
  "piss",
  "pissed",
  "pisses",
  "pissflaps",
  "porn",
  "porno",
  "pornography",
  "prick",
  "pube",
  "pubes",
  "pussy",
  "queef",
  "queer",
  "queery",
  "rape",
  "raped",
  "raper",
  "raping",
  "rapist",
  "rectum",
  "retard",
  "retarded",
  "rimjob",
  "scrotum",
  "semen",
  "sex",
  "shit",
  "shits",
  "shitty",
  "skank",
  "slut",
  "sluts",
  "smegma",
  "spunk",
  "tit",
  "tits",
  "titties",
  "twat",
  "vagina",
  "vart",
  "wank",
  "wanker",
  "whore",
  "whores",
  // Racial / ethnic slurs
  "chink",
  "chinks",
  "coolie",
  "gook",
  "gooks",
  "kike",
  "kikes",
  "negro",
  "negros",
  "paki",
  "pakis",
  "raghead",
  "ragheads",
  "sambo",
  "spic",
  "spick",
  "spics",
  "wetback",
  "wetbacks",
  "wigger",
  "wog",
  "wogs",
  "zipperhead",
]);

/** Terms that must not appear as a substring inside a combined word. */
const BLOCKED_SUBSTRINGS = [
  "asshole",
  "ballsack",
  "blowjob",
  "cocksucker",
  "faggot",
  "fudgepacker",
  "fuck",
  "jerkoff",
  "nigger",
  "nigga",
  "nutsack",
  "pissflaps",
  "rimjob",
  "retard",
  // Slurs (substring)
  "chink",
  "gook",
  "kike",
  "raghead",
  "wetback",
  "wigger",
  "zipperhead",
];

function normalizeWord(word: string) {
  return word.toLowerCase().replace(/[^a-z]/g, "");
}

/** True if the word is on the blocklist (exact or hard substring). */
export function isBlockedWord(word: string) {
  if (!CONTENT_FILTER_ENABLED) return false;
  const key = normalizeWord(word);
  if (!key) return false;
  if (BLOCKED_EXACT.has(key)) return true;
  return BLOCKED_SUBSTRINGS.some((term) => key.includes(term));
}

export function isAllowedWord(word: string) {
  if (!CONTENT_FILTER_ENABLED) return true;
  return !isBlockedWord(word);
}
