/**
 * Local offensive-word filter. Exact matches block source words from Datamuse;
 * longer substring terms catch accidental mixes (e.g. syllable joins).
 *
 * Keep lists lowercase a–z only. Prefer adding to BLOCKED_EXACT; use
 * BLOCKED_SUBSTRINGS only for terms that should never appear inside a word.
 */

const BLOCKED_EXACT = new Set([
  // Vulgar
  "anal",
  "anus",
  "arse",
  "ass",
  "asses",
  "asshole",
  "assholes",
  "ballsack",
  "bastard",
  "bastards",
  "bitch",
  "bitches",
  "bitchy",
  "blowjob",
  "bollocks",
  "boner",
  "boob",
  "boobs",
  "bugger",
  "bullshit",
  "clit",
  "clitoris",
  "cock",
  "cocks",
  "cocksucker",
  "coon",
  "crap",
  "cum",
  "cumming",
  "cunt",
  "cunts",
  "damn",
  "damned",
  "dick",
  "dicks",
  "dildo",
  "dildos",
  "dyke",
  "fag",
  "faggot",
  "faggots",
  "fags",
  "feck",
  "felch",
  "fellate",
  "fellatio",
  "feltch",
  "fuck",
  "fucked",
  "fucker",
  "fuckers",
  "fuckin",
  "fucking",
  "fucks",
  "fudgepacker",
  "goddamn",
  "hell",
  "homo",
  "jerkoff",
  "jizz",
  "labia",
  "muff",
  "nigga",
  "nigger",
  "niggers",
  "nutsack",
  "orgasm",
  "penis",
  "piss",
  "pissed",
  "pisses",
  "pissflaps",
  "porn",
  "porno",
  "pornography",
  "prick",
  "pube",
  "pubes",
  "pussy",
  "queer",
  "rape",
  "raped",
  "raper",
  "raping",
  "rapist",
  "rectum",
  "retard",
  "retarded",
  "rimjob",
  "scrotum",
  "semen",
  "sex",
  "shit",
  "shits",
  "shitty",
  "skank",
  "slut",
  "sluts",
  "smegma",
  "spunk",
  "tit",
  "tits",
  "titties",
  "twat",
  "vagina",
  "wank",
  "wanker",
  "whore",
  "whores",
  // Racial / ethnic slurs
  "chink",
  "chinks",
  "coolie",
  "gook",
  "gooks",
  "kike",
  "kikes",
  "negro",
  "negros",
  "paki",
  "pakis",
  "raghead",
  "ragheads",
  "sambo",
  "spic",
  "spick",
  "spics",
  "wetback",
  "wetbacks",
  "wog",
  "wogs",
  "zipperhead",
]);

/** Terms that must not appear as a substring inside a combined word. */
const BLOCKED_SUBSTRINGS = [
  "asshole",
  "ballsack",
  "blowjob",
  "cocksucker",
  "faggot",
  "fudgepacker",
  "fuck",
  "jerkoff",
  "nigger",
  "nigga",
  "nutsack",
  "pissflaps",
  "rimjob",
  "retard",
  // Slurs (substring)
  "chink",
  "gook",
  "kike",
  "raghead",
  "wetback",
  "zipperhead",
];

function normalizeWord(word: string) {
  return word.toLowerCase().replace(/[^a-z]/g, "");
}

/** True if the word is on the blocklist (exact or hard substring). */
export function isBlockedWord(word: string) {
  const key = normalizeWord(word);
  if (!key) return false;
  if (BLOCKED_EXACT.has(key)) return true;
  return BLOCKED_SUBSTRINGS.some((term) => key.includes(term));
}

export function isAllowedWord(word: string) {
  return !isBlockedWord(word);
}
